[package]
name = "redacta"
version = "0.0.0"
edition = "2024"
exclude = [".gitignore", "justfile", "/.github"]

[dependencies]
anyhow = { version = "1.0.98", default-features = false}
regex = { version = "1.11.1", default-features = false}