name: on_commit

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3

      - name: check
        run: just check

      - name: unit-test
        run: just unit-test

      - name: perf-test
        run: just perf-test

      - name: package
        run: just package

      - name: release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: target/redacta.tar.gz